name: MkDocs

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up cached packages
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./docs/requirements.txt
          pip install .
      - name: Build and deploy MkDocs website to GitHub Pages
        run: mkdocs gh-deploy --force
      - name: Submit sitemap URLs to IndexNow
        uses: jakob-bagterp/index-now-submit-sitemap-action@v1
        with:
          host: jakob-bagterp.github.io
          api_key: 6d71a14ac15c4c41a0c19e641f659208
          api_key_location: https://jakob-bagterp.github.io/index-now-api-key.txt
          sitemap_location: https://jakob-bagterp.github.io/timer-for-python/sitemap.xml
          endpoint: yandex
